spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/surveysystem_data?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# MyBatis 扫描(xml文件)
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.surveycenter.mapper

# 服务端口
server:
  port: 8181
